using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.Linq;
using System.Text;
using CodeFirstConfigLib;
using CodeFirstConfigLib.DataAnnotation;
using CodeFirstConfigLib.DataAnnotation.Infrastructure;
using FluentAssertions;
using Microsoft.VisualStudio.TestTools.UnitTesting;

namespace CodeFirstConfigLibTest.DataAnnotation
{
    [TestClass]
    public class DataAnnotationTes
    {
        [TestMethod]
        public void CreateDatabaseAndObserveTheSchemaManually()
        {
            Database.SetInitializer(new DropCreateDatabaseAlways<DataAnnotationContext>());

            using (var context = new DataAnnotationContext("DataAnnotation"))
            {
                var list = context.Users.ToList();
            }
        }

        [TestMethod]
        public void InsertAutoGeneratedGuid()
        {
            Database.SetInitializer(new DropCreateDatabaseAlways<DataAnnotationContext>());
            using (var context = new DataAnnotationContext("DataAnnotation"))
            {
                context.Categories.Add(new DACategory {CategoryName = "Test Generated Guid"});
                context.SaveChanges();
            }
        }

        [TestMethod]
        public void UpdateRowsWhichEnableRowVersionExpectsConcurrencyException()
        {
            Database.SetInitializer(new DropCreateDatabaseAlways<DataAnnotationContext>());
            using (var context = new DataAnnotationContext("DataAnnotation"))
            {
                context.Categories.Add(new DACategory { CategoryName = "Test Generated Guid" });
                context.SaveChanges();

                var first = context.Categories.FirstOrDefault();
                var second = first.Clone();

                first.CategoryName = "Update by First";
                second.CategoryName = "Update by Second";

                context.Categories.Attach(first);
                context.Entry(first).State = EntityState.Modified;
                context.SaveChanges();
                first.CategoryName.Should().Be("Update by First");
                

                context.Categories.Attach(second);
                context.Entry(second).State = EntityState.Modified;
                context.SaveChanges();
            }            
        }
    }
}
